#!/usr/bin/env bash
# Puts a process into the background, and kills the previous instance of the same process.
# This requires running the process '4-to_infinity_and_beyond' first.
# This assumes the script is run in the same shell/session.
CURRENT_PID=$$
pgrep -f "4-to_infinity_and_beyond" | grep -v "$CURRENT_PID" | xargs kill
./4-to_infinity_and_beyond &
